spring.application.name=demo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.zmdolvyshtesbigdwpet&password=[3z2ZQc4.?54g%jM]
spring.datasource.username=postgres.zmdolvyshtesbigdwpet
spring.datasource.password=3z2ZQc4.?54g%jM

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect